version: "3.0"

services:
  postgres-service:
    build:
      context: .
      dockerfile: ./docker-config/db/Dockerfile
    container_name: controle-estoque-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - controle-estoque-network
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  api-service:
    build:
      context: .
      dockerfile: ./docker-config/app/Dockerfile
    container_name: controle-estoque-api
    depends_on:
      - postgres-service
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - controle-estoque-network
    restart: always

networks:
  controle-estoque-network:

volumes:
  postgres_data:
