cors:
  originPatterns: http://localhost:8080,http://localhost:4200
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:postgresql://controle-estoque-postgres:5432/controleestoque?createDatabaseIfNotExist=true
#    url: jdbc:postgresql://localhost:5432/controleestoque?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
spring-doc:
  paths-to-match: /api/**
  swagger-ui:
    use-root-path: true